export const labelStage = {
  DLNT: "Drafting of Legal Notice",
  SLNT: "Sending Legal Notice",
  CSFG: "Case Filing",
  CTPG: "Court Proceedings",
  TRPH: "Trial Phase",
  ENFR: "Enforcement",
  PSEX: "Process of Execution",
  CSCR: "Case Closure",
  PRBD: "Pre Boarding",
  ONBD: "On Boarding",
  NTCE: "Notice",
  DFAP: "Default Appearance",
  MDTN: "Mediation",
  SMST: "Submission of Statements",
  STPR: "Settlement Proposals",
  FIUP: "File Upload",
  VEFI: "Verification",
  QURI: "Queries",
  REPO: "Reporting",
  LGNT: "Legal Notice",
} as const;

export const labelSubStages = {
  "CSFG#UDOC": "Uploading Documents",
  "CSFG#ADDO": "Additional Documents",
  "CSFG#DAPT": "Drafting of Petition",
  "CSFG#DREV": "Draft Review",
  "CSFG#SGCP": "Signing of Case Papers",
  "CSFG#CFSP": "Court Fee & Stamp Processing",
  "CSFG#FBCT": "Filing before Court",
  "CSFG#DROC": "Drafting of Complaint",
  "CSFG#FCPY": "Final Complaint Copy",
  "CSFG#DROP": "Drafting of Plaint",
  "CSFG#DRCR": "Drafting of Counter",
  "CSFG#NTPP": "Notice to P.P.",
  "CSFG#DRAP": "Drafting of Appeal",
  "CSFG#SDUJ": "Statutory Deposits under Judgement",
  "DLNT#AVAG": "Advocate Assignment",
  "CSFG#AVAG": "Advocate Assignment",
  "FIUP#UPAF": "Uploading of Documents",
  "FIUP#PRIC": "Pricing",
  "VEFI#AVAG": "Advocate Assignment",
  "VEFI#FICV": "File Checklist Verification",
  "QURI#RQMD": "Raising Queries",
  "REPO#SUBM": "Report Submission",
  "QURI#ASDD": "Assigning Due Date",
  "QURI#MDSC": "Close Queries",
  "SLNT#SNNT": "Sending Notice",
  "DLNT#DFNT": "Drafting of Notice",
  "NTCE#AVAG": "Advocate Assignment",
  "NTCE#DFNT": "Drafting Notice",
} as const;

export const colors = [
  "#F1C40F",
  "#E84393",
  "#E67E22",
  "#D0021B",
  "#2ECC71",
  "#FF6B6B",
  "#9C27B0",
  "#005792",
  "#006B8B",
  "#008000",
  "#FF5733",
  "#C70039",
  "#900C3F",
  "#581845",
  "#1ABC9C",
  "#3498DB",
  "#8E44AD",
  "#2C3E50",
  "#27AE60",
  "#16A085",
];

export const imageTypes = [
  "image",
  "jpg",
  "jpeg",
  "image/jpeg",
  "image/png",
  "gif",
  "svg",
  "png",
  "webp",
  "image/webp",
];

export const statusConstants = [
  {
    value: "PRBD",
    label: "Pre-boarding",
    color: "#3B3B3B",
    bg: "#f2f2f2",
  },
  {
    value: "ONBD",
    label: "On-boarding",
    color: "#1E88E5",
    bg: "#e8f3fc",
  },
  {
    value: "CSFG",
    label: "Case Filing",
    color: "#FFB300",
    bg: "#ffefcc",
  },
  {
    value: "CTPG",
    label: "Court Proceedings",
    color: "#D81B60",
    bg: "#f9d2e0",
  },
  {
    value: "TRPH",
    label: "Trial Phase",
    color: "#8E24AA",
    bg: "#efd5f6",
  },
  {
    value: "ENFR",
    label: "Enforcement",
    color: "#5E35B1",
    bg: "#e4dcf6",
  },
  {
    value: "PSEX",
    label: "Process of Execution",
    color: "#3949AB",
    bg: "#d7dff9",
  },
  {
    value: "CSCR",
    label: "Case Closure",
    color: "#219653",
    bg: "#d5f6e3",
  },
  {
    value: "NTCE",
    label: "Notice",
    color: "#F4511E",
    bg: "#ffdacc",
  },
  {
    value: "DFAP",
    label: "Default Appearance",
    color: "#6D4C41",
    bg: "#e8dcd8",
  },
  {
    value: "MDTN",
    label: "Mediation",
    color: "#43A047",
    bg: "#d3f2d9",
  },
  {
    value: "SMST",
    label: "Submission of Statements",
    color: "#FB8C00",
    bg: "#ffebd4",
  },
  {
    value: "STPR",
    label: "Settlement Proposals",
    color: "#8D6E63",
    bg: "#e9dad4",
  },
  {
    value: "FIUP",
    label: "File Upload",
    color: "#008cff",
    bg: "#dde5e9",
  },
  {
    value: "VEFI",
    label: "Verification",
    color: "#bf00ff",
    bg: "#d7dff9",
  },
  {
    value: "QURI",
    label: "Queries",
    color: "#5C6BC0",
    bg: "#e0e4f7",
  },
  {
    value: "REPO",
    label: "Reporting",
    color: "#6A1B9A",
    bg: "#ead6f6",
  },
  {
    value: "LGNT",
    label: "Legal Notice",
    color: "#D81B60",
    bg: "#f9d2e0",
  },
  {
    value: "DLNT",
    label: "Draft of Legal Notice",
    color: "#F4511E",
    bg: "#ffdacc",
  },
  {
    value: "SLNT",
    label: "Send Legal Notice",
    color: "#E53935",
    bg: "#fcdada",
  },
];

export const caseStatusConstants = [
  {
    value: "TO_START",
    label: "To Start",
    color: "#3B3B3B",
    bg: "#f2f2f2",
  },
  {
    value: "IN_PROGRESS",
    label: "In Progress",
    color: "#1E88E5",
    bg: "#e8f3fc",
  },
  {
    value: "COMPLETED",
    label: "Completed",
    color: "#219653",
    bg: "#d5f6e3",
  },
];
