/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewService_idIndexRouteImport } from './routes/review/$service_id/index'
import { Route as AppReviewsIndexRouteImport } from './routes/_app/reviews/index'
import { Route as AppRevenueStatisticsIndexRouteImport } from './routes/_app/revenue-statistics/index'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app/payments/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppManagersIndexRouteImport } from './routes/_app/managers/index'
import { Route as AppLocationsIndexRouteImport } from './routes/_app/locations/index'
import { Route as AppLitigationsIndexRouteImport } from './routes/_app/litigations/index'
import { Route as AppLegalOpinionIndexRouteImport } from './routes/_app/legal-opinion/index'
import { Route as AppEngineerPropertyValuationIndexRouteImport } from './routes/_app/engineer-property-valuation/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCreateOrganizationIndexRouteImport } from './routes/_app/create-organization/index'
import { Route as AppCreateManagerIndexRouteImport } from './routes/_app/create-manager/index'
import { Route as AppCreateLitigationIndexRouteImport } from './routes/_app/create-litigation/index'
import { Route as AppCreateLegalOpinionIndexRouteImport } from './routes/_app/create-legal-opinion/index'
import { Route as AppCreateAdvocateIndexRouteImport } from './routes/_app/create-advocate/index'
import { Route as AppAdvocatesIndexRouteImport } from './routes/_app/advocates/index'
import { Route as AppLitigationsServiceLayoutRouteImport } from './routes/_app/litigations/_service-layout'
import { Route as AppLegalOpinionServiceLayoutRouteImport } from './routes/_app/legal-opinion/_service-layout'
import { Route as AppViewManagerManager_idIndexRouteImport } from './routes/_app/view-manager/$manager_id/index'
import { Route as AppViewAdvocateAdvocate_idIndexRouteImport } from './routes/_app/view-advocate/$advocate_id/index'
import { Route as AppLitigationsAddSubStageIndexRouteImport } from './routes/_app/litigations/add-sub-stage/index'
import { Route as AppEditOrganizationOrganization_idIndexRouteImport } from './routes/_app/edit-organization/$organization_id/index'
import { Route as AppEditManagerManager_idIndexRouteImport } from './routes/_app/edit-manager/$manager_id/index'
import { Route as AppEditAdvocateAdvocate_idIndexRouteImport } from './routes/_app/edit-advocate/$advocate_id/index'
import { Route as AppServiceLayoutServiceService_idNotesRouteImport } from './routes/_app/_service-layout/service/$service_id/notes'
import { Route as AppServiceLayoutServiceService_idLogsRouteImport } from './routes/_app/_service-layout/service/$service_id/logs'
import { Route as AppServiceLayoutServiceService_idFilesRouteImport } from './routes/_app/_service-layout/service/$service_id/files'
import { Route as AppServiceLayoutServiceService_idChatRouteImport } from './routes/_app/_service-layout/service/$service_id/chat'
import { Route as AppServiceLayoutServiceService_idCaseHistoryRouteImport } from './routes/_app/_service-layout/service/$service_id/case-history'
import { Route as AppServiceLayoutServiceService_idManageIndexRouteImport } from './routes/_app/_service-layout/service/$service_id/manage/index'
import { Route as AppLitigationsServiceLayoutServiceService_idNotesRouteImport } from './routes/_app/litigations/_service-layout/service/$service_id/notes'
import { Route as AppLitigationsServiceLayoutServiceService_idLogsRouteImport } from './routes/_app/litigations/_service-layout/service/$service_id/logs'
import { Route as AppLitigationsServiceLayoutServiceService_idFilesRouteImport } from './routes/_app/litigations/_service-layout/service/$service_id/files'
import { Route as AppLitigationsServiceLayoutServiceService_idChatRouteImport } from './routes/_app/litigations/_service-layout/service/$service_id/chat'
import { Route as AppLitigationsServiceLayoutServiceService_idCaseHistoryRouteImport } from './routes/_app/litigations/_service-layout/service/$service_id/case-history'
import { Route as AppLegalOpinionServiceLayoutServiceService_idNotesRouteImport } from './routes/_app/legal-opinion/_service-layout/service/$service_id/notes'
import { Route as AppLegalOpinionServiceLayoutServiceService_idLogsRouteImport } from './routes/_app/legal-opinion/_service-layout/service/$service_id/logs'
import { Route as AppLegalOpinionServiceLayoutServiceService_idFilesRouteImport } from './routes/_app/legal-opinion/_service-layout/service/$service_id/files'
import { Route as AppLegalOpinionServiceLayoutServiceService_idChatRouteImport } from './routes/_app/legal-opinion/_service-layout/service/$service_id/chat'
import { Route as AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRouteImport } from './routes/_app/legal-opinion/_service-layout/service/$service_id/case-history'
import { Route as AppLitigationsServiceLayoutServiceService_idManageIndexRouteImport } from './routes/_app/litigations/_service-layout/service/$service_id/manage/index'
import { Route as AppLegalOpinionServiceLayoutServiceService_idManageIndexRouteImport } from './routes/_app/legal-opinion/_service-layout/service/$service_id/manage/index'
import { Route as AppServiceLayoutServiceService_idUserManageIndexRouteImport } from './routes/_app/_service-layout/service/$service_id/user/manage/index'
import { Route as AppLitigationsServiceLayoutServiceService_idUserManageIndexRouteImport } from './routes/_app/litigations/_service-layout/service/$service_id/user/manage/index'
import { Route as AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRouteImport } from './routes/_app/legal-opinion/_service-layout/service/$service_id/user/manage/index'

const AppLitigationsRouteImport = createFileRoute('/_app/litigations')()
const AppLegalOpinionRouteImport = createFileRoute('/_app/legal-opinion')()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLitigationsRoute = AppLitigationsRouteImport.update({
  id: '/litigations',
  path: '/litigations',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalOpinionRoute = AppLegalOpinionRouteImport.update({
  id: '/legal-opinion',
  path: '/legal-opinion',
  getParentRoute: () => AppRoute,
} as any)
const ReviewService_idIndexRoute = ReviewService_idIndexRouteImport.update({
  id: '/review/$service_id/',
  path: '/review/$service_id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReviewsIndexRoute = AppReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueStatisticsIndexRoute =
  AppRevenueStatisticsIndexRouteImport.update({
    id: '/revenue-statistics/',
    path: '/revenue-statistics/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppManagersIndexRoute = AppManagersIndexRouteImport.update({
  id: '/managers/',
  path: '/managers/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppRoute,
} as any)
const AppLitigationsIndexRoute = AppLitigationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLitigationsRoute,
} as any)
const AppLegalOpinionIndexRoute = AppLegalOpinionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLegalOpinionRoute,
} as any)
const AppEngineerPropertyValuationIndexRoute =
  AppEngineerPropertyValuationIndexRouteImport.update({
    id: '/engineer-property-valuation/',
    path: '/engineer-property-valuation/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateOrganizationIndexRoute =
  AppCreateOrganizationIndexRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCreateManagerIndexRoute = AppCreateManagerIndexRouteImport.update({
  id: '/create-manager/',
  path: '/create-manager/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateLitigationIndexRoute =
  AppCreateLitigationIndexRouteImport.update({
    id: '/create-litigation/',
    path: '/create-litigation/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCreateLegalOpinionIndexRoute =
  AppCreateLegalOpinionIndexRouteImport.update({
    id: '/create-legal-opinion/',
    path: '/create-legal-opinion/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCreateAdvocateIndexRoute = AppCreateAdvocateIndexRouteImport.update({
  id: '/create-advocate/',
  path: '/create-advocate/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvocatesIndexRoute = AppAdvocatesIndexRouteImport.update({
  id: '/advocates/',
  path: '/advocates/',
  getParentRoute: () => AppRoute,
} as any)
const AppLitigationsServiceLayoutRoute =
  AppLitigationsServiceLayoutRouteImport.update({
    id: '/_service-layout',
    getParentRoute: () => AppLitigationsRoute,
  } as any)
const AppLegalOpinionServiceLayoutRoute =
  AppLegalOpinionServiceLayoutRouteImport.update({
    id: '/_service-layout',
    getParentRoute: () => AppLegalOpinionRoute,
  } as any)
const AppViewManagerManager_idIndexRoute =
  AppViewManagerManager_idIndexRouteImport.update({
    id: '/view-manager/$manager_id/',
    path: '/view-manager/$manager_id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppViewAdvocateAdvocate_idIndexRoute =
  AppViewAdvocateAdvocate_idIndexRouteImport.update({
    id: '/view-advocate/$advocate_id/',
    path: '/view-advocate/$advocate_id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppLitigationsAddSubStageIndexRoute =
  AppLitigationsAddSubStageIndexRouteImport.update({
    id: '/add-sub-stage/',
    path: '/add-sub-stage/',
    getParentRoute: () => AppLitigationsRoute,
  } as any)
const AppEditOrganizationOrganization_idIndexRoute =
  AppEditOrganizationOrganization_idIndexRouteImport.update({
    id: '/edit-organization/$organization_id/',
    path: '/edit-organization/$organization_id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEditManagerManager_idIndexRoute =
  AppEditManagerManager_idIndexRouteImport.update({
    id: '/edit-manager/$manager_id/',
    path: '/edit-manager/$manager_id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEditAdvocateAdvocate_idIndexRoute =
  AppEditAdvocateAdvocate_idIndexRouteImport.update({
    id: '/edit-advocate/$advocate_id/',
    path: '/edit-advocate/$advocate_id/',
    getParentRoute: () => AppRoute,
  } as any)
const AppServiceLayoutServiceService_idNotesRoute =
  AppServiceLayoutServiceService_idNotesRouteImport.update({
    id: '/_service-layout/service/$service_id/notes',
    path: '/service/$service_id/notes',
    getParentRoute: () => AppRoute,
  } as any)
const AppServiceLayoutServiceService_idLogsRoute =
  AppServiceLayoutServiceService_idLogsRouteImport.update({
    id: '/_service-layout/service/$service_id/logs',
    path: '/service/$service_id/logs',
    getParentRoute: () => AppRoute,
  } as any)
const AppServiceLayoutServiceService_idFilesRoute =
  AppServiceLayoutServiceService_idFilesRouteImport.update({
    id: '/_service-layout/service/$service_id/files',
    path: '/service/$service_id/files',
    getParentRoute: () => AppRoute,
  } as any)
const AppServiceLayoutServiceService_idChatRoute =
  AppServiceLayoutServiceService_idChatRouteImport.update({
    id: '/_service-layout/service/$service_id/chat',
    path: '/service/$service_id/chat',
    getParentRoute: () => AppRoute,
  } as any)
const AppServiceLayoutServiceService_idCaseHistoryRoute =
  AppServiceLayoutServiceService_idCaseHistoryRouteImport.update({
    id: '/_service-layout/service/$service_id/case-history',
    path: '/service/$service_id/case-history',
    getParentRoute: () => AppRoute,
  } as any)
const AppServiceLayoutServiceService_idManageIndexRoute =
  AppServiceLayoutServiceService_idManageIndexRouteImport.update({
    id: '/_service-layout/service/$service_id/manage/',
    path: '/service/$service_id/manage/',
    getParentRoute: () => AppRoute,
  } as any)
const AppLitigationsServiceLayoutServiceService_idNotesRoute =
  AppLitigationsServiceLayoutServiceService_idNotesRouteImport.update({
    id: '/service/$service_id/notes',
    path: '/service/$service_id/notes',
    getParentRoute: () => AppLitigationsServiceLayoutRoute,
  } as any)
const AppLitigationsServiceLayoutServiceService_idLogsRoute =
  AppLitigationsServiceLayoutServiceService_idLogsRouteImport.update({
    id: '/service/$service_id/logs',
    path: '/service/$service_id/logs',
    getParentRoute: () => AppLitigationsServiceLayoutRoute,
  } as any)
const AppLitigationsServiceLayoutServiceService_idFilesRoute =
  AppLitigationsServiceLayoutServiceService_idFilesRouteImport.update({
    id: '/service/$service_id/files',
    path: '/service/$service_id/files',
    getParentRoute: () => AppLitigationsServiceLayoutRoute,
  } as any)
const AppLitigationsServiceLayoutServiceService_idChatRoute =
  AppLitigationsServiceLayoutServiceService_idChatRouteImport.update({
    id: '/service/$service_id/chat',
    path: '/service/$service_id/chat',
    getParentRoute: () => AppLitigationsServiceLayoutRoute,
  } as any)
const AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute =
  AppLitigationsServiceLayoutServiceService_idCaseHistoryRouteImport.update({
    id: '/service/$service_id/case-history',
    path: '/service/$service_id/case-history',
    getParentRoute: () => AppLitigationsServiceLayoutRoute,
  } as any)
const AppLegalOpinionServiceLayoutServiceService_idNotesRoute =
  AppLegalOpinionServiceLayoutServiceService_idNotesRouteImport.update({
    id: '/service/$service_id/notes',
    path: '/service/$service_id/notes',
    getParentRoute: () => AppLegalOpinionServiceLayoutRoute,
  } as any)
const AppLegalOpinionServiceLayoutServiceService_idLogsRoute =
  AppLegalOpinionServiceLayoutServiceService_idLogsRouteImport.update({
    id: '/service/$service_id/logs',
    path: '/service/$service_id/logs',
    getParentRoute: () => AppLegalOpinionServiceLayoutRoute,
  } as any)
const AppLegalOpinionServiceLayoutServiceService_idFilesRoute =
  AppLegalOpinionServiceLayoutServiceService_idFilesRouteImport.update({
    id: '/service/$service_id/files',
    path: '/service/$service_id/files',
    getParentRoute: () => AppLegalOpinionServiceLayoutRoute,
  } as any)
const AppLegalOpinionServiceLayoutServiceService_idChatRoute =
  AppLegalOpinionServiceLayoutServiceService_idChatRouteImport.update({
    id: '/service/$service_id/chat',
    path: '/service/$service_id/chat',
    getParentRoute: () => AppLegalOpinionServiceLayoutRoute,
  } as any)
const AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute =
  AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRouteImport.update({
    id: '/service/$service_id/case-history',
    path: '/service/$service_id/case-history',
    getParentRoute: () => AppLegalOpinionServiceLayoutRoute,
  } as any)
const AppLitigationsServiceLayoutServiceService_idManageIndexRoute =
  AppLitigationsServiceLayoutServiceService_idManageIndexRouteImport.update({
    id: '/service/$service_id/manage/',
    path: '/service/$service_id/manage/',
    getParentRoute: () => AppLitigationsServiceLayoutRoute,
  } as any)
const AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute =
  AppLegalOpinionServiceLayoutServiceService_idManageIndexRouteImport.update({
    id: '/service/$service_id/manage/',
    path: '/service/$service_id/manage/',
    getParentRoute: () => AppLegalOpinionServiceLayoutRoute,
  } as any)
const AppServiceLayoutServiceService_idUserManageIndexRoute =
  AppServiceLayoutServiceService_idUserManageIndexRouteImport.update({
    id: '/_service-layout/service/$service_id/user/manage/',
    path: '/service/$service_id/user/manage/',
    getParentRoute: () => AppRoute,
  } as any)
const AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute =
  AppLitigationsServiceLayoutServiceService_idUserManageIndexRouteImport.update(
    {
      id: '/service/$service_id/user/manage/',
      path: '/service/$service_id/user/manage/',
      getParentRoute: () => AppLitigationsServiceLayoutRoute,
    } as any,
  )
const AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute =
  AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRouteImport.update(
    {
      id: '/service/$service_id/user/manage/',
      path: '/service/$service_id/user/manage/',
      getParentRoute: () => AppLegalOpinionServiceLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/legal-opinion': typeof AppLegalOpinionServiceLayoutRouteWithChildren
  '/litigations': typeof AppLitigationsServiceLayoutRouteWithChildren
  '/advocates': typeof AppAdvocatesIndexRoute
  '/create-advocate': typeof AppCreateAdvocateIndexRoute
  '/create-legal-opinion': typeof AppCreateLegalOpinionIndexRoute
  '/create-litigation': typeof AppCreateLitigationIndexRoute
  '/create-manager': typeof AppCreateManagerIndexRoute
  '/create-organization': typeof AppCreateOrganizationIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/engineer-property-valuation': typeof AppEngineerPropertyValuationIndexRoute
  '/legal-opinion/': typeof AppLegalOpinionIndexRoute
  '/litigations/': typeof AppLitigationsIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/managers': typeof AppManagersIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/revenue-statistics': typeof AppRevenueStatisticsIndexRoute
  '/reviews': typeof AppReviewsIndexRoute
  '/review/$service_id': typeof ReviewService_idIndexRoute
  '/edit-advocate/$advocate_id': typeof AppEditAdvocateAdvocate_idIndexRoute
  '/edit-manager/$manager_id': typeof AppEditManagerManager_idIndexRoute
  '/edit-organization/$organization_id': typeof AppEditOrganizationOrganization_idIndexRoute
  '/litigations/add-sub-stage': typeof AppLitigationsAddSubStageIndexRoute
  '/view-advocate/$advocate_id': typeof AppViewAdvocateAdvocate_idIndexRoute
  '/view-manager/$manager_id': typeof AppViewManagerManager_idIndexRoute
  '/service/$service_id/case-history': typeof AppServiceLayoutServiceService_idCaseHistoryRoute
  '/service/$service_id/chat': typeof AppServiceLayoutServiceService_idChatRoute
  '/service/$service_id/files': typeof AppServiceLayoutServiceService_idFilesRoute
  '/service/$service_id/logs': typeof AppServiceLayoutServiceService_idLogsRoute
  '/service/$service_id/notes': typeof AppServiceLayoutServiceService_idNotesRoute
  '/legal-opinion/service/$service_id/case-history': typeof AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute
  '/legal-opinion/service/$service_id/chat': typeof AppLegalOpinionServiceLayoutServiceService_idChatRoute
  '/legal-opinion/service/$service_id/files': typeof AppLegalOpinionServiceLayoutServiceService_idFilesRoute
  '/legal-opinion/service/$service_id/logs': typeof AppLegalOpinionServiceLayoutServiceService_idLogsRoute
  '/legal-opinion/service/$service_id/notes': typeof AppLegalOpinionServiceLayoutServiceService_idNotesRoute
  '/litigations/service/$service_id/case-history': typeof AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute
  '/litigations/service/$service_id/chat': typeof AppLitigationsServiceLayoutServiceService_idChatRoute
  '/litigations/service/$service_id/files': typeof AppLitigationsServiceLayoutServiceService_idFilesRoute
  '/litigations/service/$service_id/logs': typeof AppLitigationsServiceLayoutServiceService_idLogsRoute
  '/litigations/service/$service_id/notes': typeof AppLitigationsServiceLayoutServiceService_idNotesRoute
  '/service/$service_id/manage': typeof AppServiceLayoutServiceService_idManageIndexRoute
  '/service/$service_id/user/manage': typeof AppServiceLayoutServiceService_idUserManageIndexRoute
  '/legal-opinion/service/$service_id/manage': typeof AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute
  '/litigations/service/$service_id/manage': typeof AppLitigationsServiceLayoutServiceService_idManageIndexRoute
  '/legal-opinion/service/$service_id/user/manage': typeof AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute
  '/litigations/service/$service_id/user/manage': typeof AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/legal-opinion': typeof AppLegalOpinionIndexRoute
  '/litigations': typeof AppLitigationsIndexRoute
  '/advocates': typeof AppAdvocatesIndexRoute
  '/create-advocate': typeof AppCreateAdvocateIndexRoute
  '/create-legal-opinion': typeof AppCreateLegalOpinionIndexRoute
  '/create-litigation': typeof AppCreateLitigationIndexRoute
  '/create-manager': typeof AppCreateManagerIndexRoute
  '/create-organization': typeof AppCreateOrganizationIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/engineer-property-valuation': typeof AppEngineerPropertyValuationIndexRoute
  '/locations': typeof AppLocationsIndexRoute
  '/managers': typeof AppManagersIndexRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/revenue-statistics': typeof AppRevenueStatisticsIndexRoute
  '/reviews': typeof AppReviewsIndexRoute
  '/review/$service_id': typeof ReviewService_idIndexRoute
  '/edit-advocate/$advocate_id': typeof AppEditAdvocateAdvocate_idIndexRoute
  '/edit-manager/$manager_id': typeof AppEditManagerManager_idIndexRoute
  '/edit-organization/$organization_id': typeof AppEditOrganizationOrganization_idIndexRoute
  '/litigations/add-sub-stage': typeof AppLitigationsAddSubStageIndexRoute
  '/view-advocate/$advocate_id': typeof AppViewAdvocateAdvocate_idIndexRoute
  '/view-manager/$manager_id': typeof AppViewManagerManager_idIndexRoute
  '/service/$service_id/case-history': typeof AppServiceLayoutServiceService_idCaseHistoryRoute
  '/service/$service_id/chat': typeof AppServiceLayoutServiceService_idChatRoute
  '/service/$service_id/files': typeof AppServiceLayoutServiceService_idFilesRoute
  '/service/$service_id/logs': typeof AppServiceLayoutServiceService_idLogsRoute
  '/service/$service_id/notes': typeof AppServiceLayoutServiceService_idNotesRoute
  '/legal-opinion/service/$service_id/case-history': typeof AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute
  '/legal-opinion/service/$service_id/chat': typeof AppLegalOpinionServiceLayoutServiceService_idChatRoute
  '/legal-opinion/service/$service_id/files': typeof AppLegalOpinionServiceLayoutServiceService_idFilesRoute
  '/legal-opinion/service/$service_id/logs': typeof AppLegalOpinionServiceLayoutServiceService_idLogsRoute
  '/legal-opinion/service/$service_id/notes': typeof AppLegalOpinionServiceLayoutServiceService_idNotesRoute
  '/litigations/service/$service_id/case-history': typeof AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute
  '/litigations/service/$service_id/chat': typeof AppLitigationsServiceLayoutServiceService_idChatRoute
  '/litigations/service/$service_id/files': typeof AppLitigationsServiceLayoutServiceService_idFilesRoute
  '/litigations/service/$service_id/logs': typeof AppLitigationsServiceLayoutServiceService_idLogsRoute
  '/litigations/service/$service_id/notes': typeof AppLitigationsServiceLayoutServiceService_idNotesRoute
  '/service/$service_id/manage': typeof AppServiceLayoutServiceService_idManageIndexRoute
  '/service/$service_id/user/manage': typeof AppServiceLayoutServiceService_idUserManageIndexRoute
  '/legal-opinion/service/$service_id/manage': typeof AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute
  '/litigations/service/$service_id/manage': typeof AppLitigationsServiceLayoutServiceService_idManageIndexRoute
  '/legal-opinion/service/$service_id/user/manage': typeof AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute
  '/litigations/service/$service_id/user/manage': typeof AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/legal-opinion': typeof AppLegalOpinionRouteWithChildren
  '/_app/legal-opinion/_service-layout': typeof AppLegalOpinionServiceLayoutRouteWithChildren
  '/_app/litigations': typeof AppLitigationsRouteWithChildren
  '/_app/litigations/_service-layout': typeof AppLitigationsServiceLayoutRouteWithChildren
  '/_app/advocates/': typeof AppAdvocatesIndexRoute
  '/_app/create-advocate/': typeof AppCreateAdvocateIndexRoute
  '/_app/create-legal-opinion/': typeof AppCreateLegalOpinionIndexRoute
  '/_app/create-litigation/': typeof AppCreateLitigationIndexRoute
  '/_app/create-manager/': typeof AppCreateManagerIndexRoute
  '/_app/create-organization/': typeof AppCreateOrganizationIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/engineer-property-valuation/': typeof AppEngineerPropertyValuationIndexRoute
  '/_app/legal-opinion/': typeof AppLegalOpinionIndexRoute
  '/_app/litigations/': typeof AppLitigationsIndexRoute
  '/_app/locations/': typeof AppLocationsIndexRoute
  '/_app/managers/': typeof AppManagersIndexRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/revenue-statistics/': typeof AppRevenueStatisticsIndexRoute
  '/_app/reviews/': typeof AppReviewsIndexRoute
  '/review/$service_id/': typeof ReviewService_idIndexRoute
  '/_app/edit-advocate/$advocate_id/': typeof AppEditAdvocateAdvocate_idIndexRoute
  '/_app/edit-manager/$manager_id/': typeof AppEditManagerManager_idIndexRoute
  '/_app/edit-organization/$organization_id/': typeof AppEditOrganizationOrganization_idIndexRoute
  '/_app/litigations/add-sub-stage/': typeof AppLitigationsAddSubStageIndexRoute
  '/_app/view-advocate/$advocate_id/': typeof AppViewAdvocateAdvocate_idIndexRoute
  '/_app/view-manager/$manager_id/': typeof AppViewManagerManager_idIndexRoute
  '/_app/_service-layout/service/$service_id/case-history': typeof AppServiceLayoutServiceService_idCaseHistoryRoute
  '/_app/_service-layout/service/$service_id/chat': typeof AppServiceLayoutServiceService_idChatRoute
  '/_app/_service-layout/service/$service_id/files': typeof AppServiceLayoutServiceService_idFilesRoute
  '/_app/_service-layout/service/$service_id/logs': typeof AppServiceLayoutServiceService_idLogsRoute
  '/_app/_service-layout/service/$service_id/notes': typeof AppServiceLayoutServiceService_idNotesRoute
  '/_app/legal-opinion/_service-layout/service/$service_id/case-history': typeof AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute
  '/_app/legal-opinion/_service-layout/service/$service_id/chat': typeof AppLegalOpinionServiceLayoutServiceService_idChatRoute
  '/_app/legal-opinion/_service-layout/service/$service_id/files': typeof AppLegalOpinionServiceLayoutServiceService_idFilesRoute
  '/_app/legal-opinion/_service-layout/service/$service_id/logs': typeof AppLegalOpinionServiceLayoutServiceService_idLogsRoute
  '/_app/legal-opinion/_service-layout/service/$service_id/notes': typeof AppLegalOpinionServiceLayoutServiceService_idNotesRoute
  '/_app/litigations/_service-layout/service/$service_id/case-history': typeof AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute
  '/_app/litigations/_service-layout/service/$service_id/chat': typeof AppLitigationsServiceLayoutServiceService_idChatRoute
  '/_app/litigations/_service-layout/service/$service_id/files': typeof AppLitigationsServiceLayoutServiceService_idFilesRoute
  '/_app/litigations/_service-layout/service/$service_id/logs': typeof AppLitigationsServiceLayoutServiceService_idLogsRoute
  '/_app/litigations/_service-layout/service/$service_id/notes': typeof AppLitigationsServiceLayoutServiceService_idNotesRoute
  '/_app/_service-layout/service/$service_id/manage/': typeof AppServiceLayoutServiceService_idManageIndexRoute
  '/_app/_service-layout/service/$service_id/user/manage/': typeof AppServiceLayoutServiceService_idUserManageIndexRoute
  '/_app/legal-opinion/_service-layout/service/$service_id/manage/': typeof AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute
  '/_app/litigations/_service-layout/service/$service_id/manage/': typeof AppLitigationsServiceLayoutServiceService_idManageIndexRoute
  '/_app/legal-opinion/_service-layout/service/$service_id/user/manage/': typeof AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute
  '/_app/litigations/_service-layout/service/$service_id/user/manage/': typeof AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/legal-opinion'
    | '/litigations'
    | '/advocates'
    | '/create-advocate'
    | '/create-legal-opinion'
    | '/create-litigation'
    | '/create-manager'
    | '/create-organization'
    | '/dashboard'
    | '/engineer-property-valuation'
    | '/legal-opinion/'
    | '/litigations/'
    | '/locations'
    | '/managers'
    | '/organizations'
    | '/payments'
    | '/revenue-statistics'
    | '/reviews'
    | '/review/$service_id'
    | '/edit-advocate/$advocate_id'
    | '/edit-manager/$manager_id'
    | '/edit-organization/$organization_id'
    | '/litigations/add-sub-stage'
    | '/view-advocate/$advocate_id'
    | '/view-manager/$manager_id'
    | '/service/$service_id/case-history'
    | '/service/$service_id/chat'
    | '/service/$service_id/files'
    | '/service/$service_id/logs'
    | '/service/$service_id/notes'
    | '/legal-opinion/service/$service_id/case-history'
    | '/legal-opinion/service/$service_id/chat'
    | '/legal-opinion/service/$service_id/files'
    | '/legal-opinion/service/$service_id/logs'
    | '/legal-opinion/service/$service_id/notes'
    | '/litigations/service/$service_id/case-history'
    | '/litigations/service/$service_id/chat'
    | '/litigations/service/$service_id/files'
    | '/litigations/service/$service_id/logs'
    | '/litigations/service/$service_id/notes'
    | '/service/$service_id/manage'
    | '/service/$service_id/user/manage'
    | '/legal-opinion/service/$service_id/manage'
    | '/litigations/service/$service_id/manage'
    | '/legal-opinion/service/$service_id/user/manage'
    | '/litigations/service/$service_id/user/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/legal-opinion'
    | '/litigations'
    | '/advocates'
    | '/create-advocate'
    | '/create-legal-opinion'
    | '/create-litigation'
    | '/create-manager'
    | '/create-organization'
    | '/dashboard'
    | '/engineer-property-valuation'
    | '/locations'
    | '/managers'
    | '/organizations'
    | '/payments'
    | '/revenue-statistics'
    | '/reviews'
    | '/review/$service_id'
    | '/edit-advocate/$advocate_id'
    | '/edit-manager/$manager_id'
    | '/edit-organization/$organization_id'
    | '/litigations/add-sub-stage'
    | '/view-advocate/$advocate_id'
    | '/view-manager/$manager_id'
    | '/service/$service_id/case-history'
    | '/service/$service_id/chat'
    | '/service/$service_id/files'
    | '/service/$service_id/logs'
    | '/service/$service_id/notes'
    | '/legal-opinion/service/$service_id/case-history'
    | '/legal-opinion/service/$service_id/chat'
    | '/legal-opinion/service/$service_id/files'
    | '/legal-opinion/service/$service_id/logs'
    | '/legal-opinion/service/$service_id/notes'
    | '/litigations/service/$service_id/case-history'
    | '/litigations/service/$service_id/chat'
    | '/litigations/service/$service_id/files'
    | '/litigations/service/$service_id/logs'
    | '/litigations/service/$service_id/notes'
    | '/service/$service_id/manage'
    | '/service/$service_id/user/manage'
    | '/legal-opinion/service/$service_id/manage'
    | '/litigations/service/$service_id/manage'
    | '/legal-opinion/service/$service_id/user/manage'
    | '/litigations/service/$service_id/user/manage'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/legal-opinion'
    | '/_app/legal-opinion/_service-layout'
    | '/_app/litigations'
    | '/_app/litigations/_service-layout'
    | '/_app/advocates/'
    | '/_app/create-advocate/'
    | '/_app/create-legal-opinion/'
    | '/_app/create-litigation/'
    | '/_app/create-manager/'
    | '/_app/create-organization/'
    | '/_app/dashboard/'
    | '/_app/engineer-property-valuation/'
    | '/_app/legal-opinion/'
    | '/_app/litigations/'
    | '/_app/locations/'
    | '/_app/managers/'
    | '/_app/organizations/'
    | '/_app/payments/'
    | '/_app/revenue-statistics/'
    | '/_app/reviews/'
    | '/review/$service_id/'
    | '/_app/edit-advocate/$advocate_id/'
    | '/_app/edit-manager/$manager_id/'
    | '/_app/edit-organization/$organization_id/'
    | '/_app/litigations/add-sub-stage/'
    | '/_app/view-advocate/$advocate_id/'
    | '/_app/view-manager/$manager_id/'
    | '/_app/_service-layout/service/$service_id/case-history'
    | '/_app/_service-layout/service/$service_id/chat'
    | '/_app/_service-layout/service/$service_id/files'
    | '/_app/_service-layout/service/$service_id/logs'
    | '/_app/_service-layout/service/$service_id/notes'
    | '/_app/legal-opinion/_service-layout/service/$service_id/case-history'
    | '/_app/legal-opinion/_service-layout/service/$service_id/chat'
    | '/_app/legal-opinion/_service-layout/service/$service_id/files'
    | '/_app/legal-opinion/_service-layout/service/$service_id/logs'
    | '/_app/legal-opinion/_service-layout/service/$service_id/notes'
    | '/_app/litigations/_service-layout/service/$service_id/case-history'
    | '/_app/litigations/_service-layout/service/$service_id/chat'
    | '/_app/litigations/_service-layout/service/$service_id/files'
    | '/_app/litigations/_service-layout/service/$service_id/logs'
    | '/_app/litigations/_service-layout/service/$service_id/notes'
    | '/_app/_service-layout/service/$service_id/manage/'
    | '/_app/_service-layout/service/$service_id/user/manage/'
    | '/_app/legal-opinion/_service-layout/service/$service_id/manage/'
    | '/_app/litigations/_service-layout/service/$service_id/manage/'
    | '/_app/legal-opinion/_service-layout/service/$service_id/user/manage/'
    | '/_app/litigations/_service-layout/service/$service_id/user/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReviewService_idIndexRoute: typeof ReviewService_idIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/litigations': {
      id: '/_app/litigations'
      path: '/litigations'
      fullPath: '/litigations'
      preLoaderRoute: typeof AppLitigationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal-opinion': {
      id: '/_app/legal-opinion'
      path: '/legal-opinion'
      fullPath: '/legal-opinion'
      preLoaderRoute: typeof AppLegalOpinionRouteImport
      parentRoute: typeof AppRoute
    }
    '/review/$service_id/': {
      id: '/review/$service_id/'
      path: '/review/$service_id'
      fullPath: '/review/$service_id'
      preLoaderRoute: typeof ReviewService_idIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reviews/': {
      id: '/_app/reviews/'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revenue-statistics/': {
      id: '/_app/revenue-statistics/'
      path: '/revenue-statistics'
      fullPath: '/revenue-statistics'
      preLoaderRoute: typeof AppRevenueStatisticsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/managers/': {
      id: '/_app/managers/'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof AppManagersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations/': {
      id: '/_app/locations/'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/litigations/': {
      id: '/_app/litigations/'
      path: '/'
      fullPath: '/litigations/'
      preLoaderRoute: typeof AppLitigationsIndexRouteImport
      parentRoute: typeof AppLitigationsRoute
    }
    '/_app/legal-opinion/': {
      id: '/_app/legal-opinion/'
      path: '/'
      fullPath: '/legal-opinion/'
      preLoaderRoute: typeof AppLegalOpinionIndexRouteImport
      parentRoute: typeof AppLegalOpinionRoute
    }
    '/_app/engineer-property-valuation/': {
      id: '/_app/engineer-property-valuation/'
      path: '/engineer-property-valuation'
      fullPath: '/engineer-property-valuation'
      preLoaderRoute: typeof AppEngineerPropertyValuationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-organization/': {
      id: '/_app/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof AppCreateOrganizationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-manager/': {
      id: '/_app/create-manager/'
      path: '/create-manager'
      fullPath: '/create-manager'
      preLoaderRoute: typeof AppCreateManagerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-litigation/': {
      id: '/_app/create-litigation/'
      path: '/create-litigation'
      fullPath: '/create-litigation'
      preLoaderRoute: typeof AppCreateLitigationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-legal-opinion/': {
      id: '/_app/create-legal-opinion/'
      path: '/create-legal-opinion'
      fullPath: '/create-legal-opinion'
      preLoaderRoute: typeof AppCreateLegalOpinionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-advocate/': {
      id: '/_app/create-advocate/'
      path: '/create-advocate'
      fullPath: '/create-advocate'
      preLoaderRoute: typeof AppCreateAdvocateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advocates/': {
      id: '/_app/advocates/'
      path: '/advocates'
      fullPath: '/advocates'
      preLoaderRoute: typeof AppAdvocatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/litigations/_service-layout': {
      id: '/_app/litigations/_service-layout'
      path: '/litigations'
      fullPath: '/litigations'
      preLoaderRoute: typeof AppLitigationsServiceLayoutRouteImport
      parentRoute: typeof AppLitigationsRoute
    }
    '/_app/legal-opinion/_service-layout': {
      id: '/_app/legal-opinion/_service-layout'
      path: '/legal-opinion'
      fullPath: '/legal-opinion'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutRouteImport
      parentRoute: typeof AppLegalOpinionRoute
    }
    '/_app/view-manager/$manager_id/': {
      id: '/_app/view-manager/$manager_id/'
      path: '/view-manager/$manager_id'
      fullPath: '/view-manager/$manager_id'
      preLoaderRoute: typeof AppViewManagerManager_idIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/view-advocate/$advocate_id/': {
      id: '/_app/view-advocate/$advocate_id/'
      path: '/view-advocate/$advocate_id'
      fullPath: '/view-advocate/$advocate_id'
      preLoaderRoute: typeof AppViewAdvocateAdvocate_idIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/litigations/add-sub-stage/': {
      id: '/_app/litigations/add-sub-stage/'
      path: '/add-sub-stage'
      fullPath: '/litigations/add-sub-stage'
      preLoaderRoute: typeof AppLitigationsAddSubStageIndexRouteImport
      parentRoute: typeof AppLitigationsRoute
    }
    '/_app/edit-organization/$organization_id/': {
      id: '/_app/edit-organization/$organization_id/'
      path: '/edit-organization/$organization_id'
      fullPath: '/edit-organization/$organization_id'
      preLoaderRoute: typeof AppEditOrganizationOrganization_idIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/edit-manager/$manager_id/': {
      id: '/_app/edit-manager/$manager_id/'
      path: '/edit-manager/$manager_id'
      fullPath: '/edit-manager/$manager_id'
      preLoaderRoute: typeof AppEditManagerManager_idIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/edit-advocate/$advocate_id/': {
      id: '/_app/edit-advocate/$advocate_id/'
      path: '/edit-advocate/$advocate_id'
      fullPath: '/edit-advocate/$advocate_id'
      preLoaderRoute: typeof AppEditAdvocateAdvocate_idIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_service-layout/service/$service_id/notes': {
      id: '/_app/_service-layout/service/$service_id/notes'
      path: '/service/$service_id/notes'
      fullPath: '/service/$service_id/notes'
      preLoaderRoute: typeof AppServiceLayoutServiceService_idNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_service-layout/service/$service_id/logs': {
      id: '/_app/_service-layout/service/$service_id/logs'
      path: '/service/$service_id/logs'
      fullPath: '/service/$service_id/logs'
      preLoaderRoute: typeof AppServiceLayoutServiceService_idLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_service-layout/service/$service_id/files': {
      id: '/_app/_service-layout/service/$service_id/files'
      path: '/service/$service_id/files'
      fullPath: '/service/$service_id/files'
      preLoaderRoute: typeof AppServiceLayoutServiceService_idFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_service-layout/service/$service_id/chat': {
      id: '/_app/_service-layout/service/$service_id/chat'
      path: '/service/$service_id/chat'
      fullPath: '/service/$service_id/chat'
      preLoaderRoute: typeof AppServiceLayoutServiceService_idChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_service-layout/service/$service_id/case-history': {
      id: '/_app/_service-layout/service/$service_id/case-history'
      path: '/service/$service_id/case-history'
      fullPath: '/service/$service_id/case-history'
      preLoaderRoute: typeof AppServiceLayoutServiceService_idCaseHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_service-layout/service/$service_id/manage/': {
      id: '/_app/_service-layout/service/$service_id/manage/'
      path: '/service/$service_id/manage'
      fullPath: '/service/$service_id/manage'
      preLoaderRoute: typeof AppServiceLayoutServiceService_idManageIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/litigations/_service-layout/service/$service_id/notes': {
      id: '/_app/litigations/_service-layout/service/$service_id/notes'
      path: '/service/$service_id/notes'
      fullPath: '/litigations/service/$service_id/notes'
      preLoaderRoute: typeof AppLitigationsServiceLayoutServiceService_idNotesRouteImport
      parentRoute: typeof AppLitigationsServiceLayoutRoute
    }
    '/_app/litigations/_service-layout/service/$service_id/logs': {
      id: '/_app/litigations/_service-layout/service/$service_id/logs'
      path: '/service/$service_id/logs'
      fullPath: '/litigations/service/$service_id/logs'
      preLoaderRoute: typeof AppLitigationsServiceLayoutServiceService_idLogsRouteImport
      parentRoute: typeof AppLitigationsServiceLayoutRoute
    }
    '/_app/litigations/_service-layout/service/$service_id/files': {
      id: '/_app/litigations/_service-layout/service/$service_id/files'
      path: '/service/$service_id/files'
      fullPath: '/litigations/service/$service_id/files'
      preLoaderRoute: typeof AppLitigationsServiceLayoutServiceService_idFilesRouteImport
      parentRoute: typeof AppLitigationsServiceLayoutRoute
    }
    '/_app/litigations/_service-layout/service/$service_id/chat': {
      id: '/_app/litigations/_service-layout/service/$service_id/chat'
      path: '/service/$service_id/chat'
      fullPath: '/litigations/service/$service_id/chat'
      preLoaderRoute: typeof AppLitigationsServiceLayoutServiceService_idChatRouteImport
      parentRoute: typeof AppLitigationsServiceLayoutRoute
    }
    '/_app/litigations/_service-layout/service/$service_id/case-history': {
      id: '/_app/litigations/_service-layout/service/$service_id/case-history'
      path: '/service/$service_id/case-history'
      fullPath: '/litigations/service/$service_id/case-history'
      preLoaderRoute: typeof AppLitigationsServiceLayoutServiceService_idCaseHistoryRouteImport
      parentRoute: typeof AppLitigationsServiceLayoutRoute
    }
    '/_app/legal-opinion/_service-layout/service/$service_id/notes': {
      id: '/_app/legal-opinion/_service-layout/service/$service_id/notes'
      path: '/service/$service_id/notes'
      fullPath: '/legal-opinion/service/$service_id/notes'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutServiceService_idNotesRouteImport
      parentRoute: typeof AppLegalOpinionServiceLayoutRoute
    }
    '/_app/legal-opinion/_service-layout/service/$service_id/logs': {
      id: '/_app/legal-opinion/_service-layout/service/$service_id/logs'
      path: '/service/$service_id/logs'
      fullPath: '/legal-opinion/service/$service_id/logs'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutServiceService_idLogsRouteImport
      parentRoute: typeof AppLegalOpinionServiceLayoutRoute
    }
    '/_app/legal-opinion/_service-layout/service/$service_id/files': {
      id: '/_app/legal-opinion/_service-layout/service/$service_id/files'
      path: '/service/$service_id/files'
      fullPath: '/legal-opinion/service/$service_id/files'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutServiceService_idFilesRouteImport
      parentRoute: typeof AppLegalOpinionServiceLayoutRoute
    }
    '/_app/legal-opinion/_service-layout/service/$service_id/chat': {
      id: '/_app/legal-opinion/_service-layout/service/$service_id/chat'
      path: '/service/$service_id/chat'
      fullPath: '/legal-opinion/service/$service_id/chat'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutServiceService_idChatRouteImport
      parentRoute: typeof AppLegalOpinionServiceLayoutRoute
    }
    '/_app/legal-opinion/_service-layout/service/$service_id/case-history': {
      id: '/_app/legal-opinion/_service-layout/service/$service_id/case-history'
      path: '/service/$service_id/case-history'
      fullPath: '/legal-opinion/service/$service_id/case-history'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRouteImport
      parentRoute: typeof AppLegalOpinionServiceLayoutRoute
    }
    '/_app/litigations/_service-layout/service/$service_id/manage/': {
      id: '/_app/litigations/_service-layout/service/$service_id/manage/'
      path: '/service/$service_id/manage'
      fullPath: '/litigations/service/$service_id/manage'
      preLoaderRoute: typeof AppLitigationsServiceLayoutServiceService_idManageIndexRouteImport
      parentRoute: typeof AppLitigationsServiceLayoutRoute
    }
    '/_app/legal-opinion/_service-layout/service/$service_id/manage/': {
      id: '/_app/legal-opinion/_service-layout/service/$service_id/manage/'
      path: '/service/$service_id/manage'
      fullPath: '/legal-opinion/service/$service_id/manage'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutServiceService_idManageIndexRouteImport
      parentRoute: typeof AppLegalOpinionServiceLayoutRoute
    }
    '/_app/_service-layout/service/$service_id/user/manage/': {
      id: '/_app/_service-layout/service/$service_id/user/manage/'
      path: '/service/$service_id/user/manage'
      fullPath: '/service/$service_id/user/manage'
      preLoaderRoute: typeof AppServiceLayoutServiceService_idUserManageIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/litigations/_service-layout/service/$service_id/user/manage/': {
      id: '/_app/litigations/_service-layout/service/$service_id/user/manage/'
      path: '/service/$service_id/user/manage'
      fullPath: '/litigations/service/$service_id/user/manage'
      preLoaderRoute: typeof AppLitigationsServiceLayoutServiceService_idUserManageIndexRouteImport
      parentRoute: typeof AppLitigationsServiceLayoutRoute
    }
    '/_app/legal-opinion/_service-layout/service/$service_id/user/manage/': {
      id: '/_app/legal-opinion/_service-layout/service/$service_id/user/manage/'
      path: '/service/$service_id/user/manage'
      fullPath: '/legal-opinion/service/$service_id/user/manage'
      preLoaderRoute: typeof AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRouteImport
      parentRoute: typeof AppLegalOpinionServiceLayoutRoute
    }
  }
}

interface AppLegalOpinionServiceLayoutRouteChildren {
  AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute: typeof AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute
  AppLegalOpinionServiceLayoutServiceService_idChatRoute: typeof AppLegalOpinionServiceLayoutServiceService_idChatRoute
  AppLegalOpinionServiceLayoutServiceService_idFilesRoute: typeof AppLegalOpinionServiceLayoutServiceService_idFilesRoute
  AppLegalOpinionServiceLayoutServiceService_idLogsRoute: typeof AppLegalOpinionServiceLayoutServiceService_idLogsRoute
  AppLegalOpinionServiceLayoutServiceService_idNotesRoute: typeof AppLegalOpinionServiceLayoutServiceService_idNotesRoute
  AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute: typeof AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute
  AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute: typeof AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute
}

const AppLegalOpinionServiceLayoutRouteChildren: AppLegalOpinionServiceLayoutRouteChildren =
  {
    AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute:
      AppLegalOpinionServiceLayoutServiceService_idCaseHistoryRoute,
    AppLegalOpinionServiceLayoutServiceService_idChatRoute:
      AppLegalOpinionServiceLayoutServiceService_idChatRoute,
    AppLegalOpinionServiceLayoutServiceService_idFilesRoute:
      AppLegalOpinionServiceLayoutServiceService_idFilesRoute,
    AppLegalOpinionServiceLayoutServiceService_idLogsRoute:
      AppLegalOpinionServiceLayoutServiceService_idLogsRoute,
    AppLegalOpinionServiceLayoutServiceService_idNotesRoute:
      AppLegalOpinionServiceLayoutServiceService_idNotesRoute,
    AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute:
      AppLegalOpinionServiceLayoutServiceService_idManageIndexRoute,
    AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute:
      AppLegalOpinionServiceLayoutServiceService_idUserManageIndexRoute,
  }

const AppLegalOpinionServiceLayoutRouteWithChildren =
  AppLegalOpinionServiceLayoutRoute._addFileChildren(
    AppLegalOpinionServiceLayoutRouteChildren,
  )

interface AppLegalOpinionRouteChildren {
  AppLegalOpinionServiceLayoutRoute: typeof AppLegalOpinionServiceLayoutRouteWithChildren
  AppLegalOpinionIndexRoute: typeof AppLegalOpinionIndexRoute
}

const AppLegalOpinionRouteChildren: AppLegalOpinionRouteChildren = {
  AppLegalOpinionServiceLayoutRoute:
    AppLegalOpinionServiceLayoutRouteWithChildren,
  AppLegalOpinionIndexRoute: AppLegalOpinionIndexRoute,
}

const AppLegalOpinionRouteWithChildren = AppLegalOpinionRoute._addFileChildren(
  AppLegalOpinionRouteChildren,
)

interface AppLitigationsServiceLayoutRouteChildren {
  AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute: typeof AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute
  AppLitigationsServiceLayoutServiceService_idChatRoute: typeof AppLitigationsServiceLayoutServiceService_idChatRoute
  AppLitigationsServiceLayoutServiceService_idFilesRoute: typeof AppLitigationsServiceLayoutServiceService_idFilesRoute
  AppLitigationsServiceLayoutServiceService_idLogsRoute: typeof AppLitigationsServiceLayoutServiceService_idLogsRoute
  AppLitigationsServiceLayoutServiceService_idNotesRoute: typeof AppLitigationsServiceLayoutServiceService_idNotesRoute
  AppLitigationsServiceLayoutServiceService_idManageIndexRoute: typeof AppLitigationsServiceLayoutServiceService_idManageIndexRoute
  AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute: typeof AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute
}

const AppLitigationsServiceLayoutRouteChildren: AppLitigationsServiceLayoutRouteChildren =
  {
    AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute:
      AppLitigationsServiceLayoutServiceService_idCaseHistoryRoute,
    AppLitigationsServiceLayoutServiceService_idChatRoute:
      AppLitigationsServiceLayoutServiceService_idChatRoute,
    AppLitigationsServiceLayoutServiceService_idFilesRoute:
      AppLitigationsServiceLayoutServiceService_idFilesRoute,
    AppLitigationsServiceLayoutServiceService_idLogsRoute:
      AppLitigationsServiceLayoutServiceService_idLogsRoute,
    AppLitigationsServiceLayoutServiceService_idNotesRoute:
      AppLitigationsServiceLayoutServiceService_idNotesRoute,
    AppLitigationsServiceLayoutServiceService_idManageIndexRoute:
      AppLitigationsServiceLayoutServiceService_idManageIndexRoute,
    AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute:
      AppLitigationsServiceLayoutServiceService_idUserManageIndexRoute,
  }

const AppLitigationsServiceLayoutRouteWithChildren =
  AppLitigationsServiceLayoutRoute._addFileChildren(
    AppLitigationsServiceLayoutRouteChildren,
  )

interface AppLitigationsRouteChildren {
  AppLitigationsServiceLayoutRoute: typeof AppLitigationsServiceLayoutRouteWithChildren
  AppLitigationsIndexRoute: typeof AppLitigationsIndexRoute
  AppLitigationsAddSubStageIndexRoute: typeof AppLitigationsAddSubStageIndexRoute
}

const AppLitigationsRouteChildren: AppLitigationsRouteChildren = {
  AppLitigationsServiceLayoutRoute:
    AppLitigationsServiceLayoutRouteWithChildren,
  AppLitigationsIndexRoute: AppLitigationsIndexRoute,
  AppLitigationsAddSubStageIndexRoute: AppLitigationsAddSubStageIndexRoute,
}

const AppLitigationsRouteWithChildren = AppLitigationsRoute._addFileChildren(
  AppLitigationsRouteChildren,
)

interface AppRouteChildren {
  AppLegalOpinionRoute: typeof AppLegalOpinionRouteWithChildren
  AppLitigationsRoute: typeof AppLitigationsRouteWithChildren
  AppAdvocatesIndexRoute: typeof AppAdvocatesIndexRoute
  AppCreateAdvocateIndexRoute: typeof AppCreateAdvocateIndexRoute
  AppCreateLegalOpinionIndexRoute: typeof AppCreateLegalOpinionIndexRoute
  AppCreateLitigationIndexRoute: typeof AppCreateLitigationIndexRoute
  AppCreateManagerIndexRoute: typeof AppCreateManagerIndexRoute
  AppCreateOrganizationIndexRoute: typeof AppCreateOrganizationIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEngineerPropertyValuationIndexRoute: typeof AppEngineerPropertyValuationIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppManagersIndexRoute: typeof AppManagersIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppRevenueStatisticsIndexRoute: typeof AppRevenueStatisticsIndexRoute
  AppReviewsIndexRoute: typeof AppReviewsIndexRoute
  AppEditAdvocateAdvocate_idIndexRoute: typeof AppEditAdvocateAdvocate_idIndexRoute
  AppEditManagerManager_idIndexRoute: typeof AppEditManagerManager_idIndexRoute
  AppEditOrganizationOrganization_idIndexRoute: typeof AppEditOrganizationOrganization_idIndexRoute
  AppViewAdvocateAdvocate_idIndexRoute: typeof AppViewAdvocateAdvocate_idIndexRoute
  AppViewManagerManager_idIndexRoute: typeof AppViewManagerManager_idIndexRoute
  AppServiceLayoutServiceService_idCaseHistoryRoute: typeof AppServiceLayoutServiceService_idCaseHistoryRoute
  AppServiceLayoutServiceService_idChatRoute: typeof AppServiceLayoutServiceService_idChatRoute
  AppServiceLayoutServiceService_idFilesRoute: typeof AppServiceLayoutServiceService_idFilesRoute
  AppServiceLayoutServiceService_idLogsRoute: typeof AppServiceLayoutServiceService_idLogsRoute
  AppServiceLayoutServiceService_idNotesRoute: typeof AppServiceLayoutServiceService_idNotesRoute
  AppServiceLayoutServiceService_idManageIndexRoute: typeof AppServiceLayoutServiceService_idManageIndexRoute
  AppServiceLayoutServiceService_idUserManageIndexRoute: typeof AppServiceLayoutServiceService_idUserManageIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLegalOpinionRoute: AppLegalOpinionRouteWithChildren,
  AppLitigationsRoute: AppLitigationsRouteWithChildren,
  AppAdvocatesIndexRoute: AppAdvocatesIndexRoute,
  AppCreateAdvocateIndexRoute: AppCreateAdvocateIndexRoute,
  AppCreateLegalOpinionIndexRoute: AppCreateLegalOpinionIndexRoute,
  AppCreateLitigationIndexRoute: AppCreateLitigationIndexRoute,
  AppCreateManagerIndexRoute: AppCreateManagerIndexRoute,
  AppCreateOrganizationIndexRoute: AppCreateOrganizationIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEngineerPropertyValuationIndexRoute:
    AppEngineerPropertyValuationIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppManagersIndexRoute: AppManagersIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppRevenueStatisticsIndexRoute: AppRevenueStatisticsIndexRoute,
  AppReviewsIndexRoute: AppReviewsIndexRoute,
  AppEditAdvocateAdvocate_idIndexRoute: AppEditAdvocateAdvocate_idIndexRoute,
  AppEditManagerManager_idIndexRoute: AppEditManagerManager_idIndexRoute,
  AppEditOrganizationOrganization_idIndexRoute:
    AppEditOrganizationOrganization_idIndexRoute,
  AppViewAdvocateAdvocate_idIndexRoute: AppViewAdvocateAdvocate_idIndexRoute,
  AppViewManagerManager_idIndexRoute: AppViewManagerManager_idIndexRoute,
  AppServiceLayoutServiceService_idCaseHistoryRoute:
    AppServiceLayoutServiceService_idCaseHistoryRoute,
  AppServiceLayoutServiceService_idChatRoute:
    AppServiceLayoutServiceService_idChatRoute,
  AppServiceLayoutServiceService_idFilesRoute:
    AppServiceLayoutServiceService_idFilesRoute,
  AppServiceLayoutServiceService_idLogsRoute:
    AppServiceLayoutServiceService_idLogsRoute,
  AppServiceLayoutServiceService_idNotesRoute:
    AppServiceLayoutServiceService_idNotesRoute,
  AppServiceLayoutServiceService_idManageIndexRoute:
    AppServiceLayoutServiceService_idManageIndexRoute,
  AppServiceLayoutServiceService_idUserManageIndexRoute:
    AppServiceLayoutServiceService_idUserManageIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReviewService_idIndexRoute: ReviewService_idIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
